ARMGNU ?= aarch64-linux-gnu

COPS = -Wall -nostdlib -Iinclude -mgeneral-regs-only -ffreestanding -nostartfiles -g -O0
ASMOPS = -Iinclude  -D__ASSEMBLY__ -g -O0

BUILD_DIR = build
SRC_DIR = src

offsets-file := include/asm-offsets.h

define sed-y
    "/^->/{s:->#\(.*\):/* \1 */:; \
    s:^->\([^ ]*\) [\$$#]*\([^ ]*\) \(.*\):#define \1 \2 /* \3 */:; \
    s:->::; p;}"
endef

define cmd_offsets
    (set -e; \
     echo "#ifndef __ASM_OFFSETS_H__"; \
     echo "#define __ASM_OFFSETS_H__"; \
     echo "/*"; \
     echo " * DO NOT MODIFY."; \
     echo " *"; \
     echo " * This file was generated by Kbuild"; \
     echo " *"; \
     echo " */"; \
     echo ""; \
     sed -ne $(sed-y) $<; \
     echo ""; \
     echo "#endif" ) > $@
endef

$(BUILD_DIR)/asm-offsets.s : src/asm-offsets.c
	mkdir -p $(@D)
	gcc -Iinclude -S $< -o $@


all : rpios.bin

clean :
	rm -rf $(BUILD_DIR) *.img
run :
	qemu-system-aarch64 -machine raspi3 -nographic -kernel rpios.img -serial mon:stdio

debug : 
	qemu-system-aarch64 -machine raspi3 -nographic -kernel rpios.img  -S -s

$(BUILD_DIR)/%_c.o: $(SRC_DIR)/%.c
	mkdir -p $(@D)
	$(ARMGNU)-gcc $(COPS) -MMD -c $< -o $@

$(BUILD_DIR)/%_s.o: $(SRC_DIR)/%.S
	$(ARMGNU)-gcc $(ASMOPS) -MMD -c $< -o $@

$(offsets-file) : $(BUILD_DIR)/asm-offsets.s
	@$(cmd_offsets)

C_FILES = $(filter-out $(SRC_DIR)/asm-offsets.c, $(wildcard $(SRC_DIR)/*.c))

ASM_FILES = $(wildcard $(SRC_DIR)/*.S)
OBJ_FILES = $(C_FILES:$(SRC_DIR)/%.c=$(BUILD_DIR)/%_c.o)
OBJ_FILES += $(ASM_FILES:$(SRC_DIR)/%.S=$(BUILD_DIR)/%_s.o)

DEP_FILES = $(OBJ_FILES:%.o=%.d)
-include $(DEP_FILES)

rpios.bin: $(SRC_DIR)/linker.ld $(OBJ_FILES)
	$(ARMGNU)-ld -T $(SRC_DIR)/linker.ld -o $(BUILD_DIR)/rpios.elf  $(OBJ_FILES)
	$(ARMGNU)-objcopy $(BUILD_DIR)/rpios.elf -O binary rpios.img
