#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define S_FRAME_SIZE 264 /* sizeof(struct pt_regs) */
#define THREAD_CPU_CONTEXT 0 /* offsetof(struct task_struct, cpu_context) */
#define TIF_PREEMPT_COUNT 120 /* offsetof(struct task_struct, preempt_count) */
#define TIF_NEED_RESCHED 128 /* offsetof(struct task_struct, flag) */

#endif
